# Sistemas de ecuaciones
<p><code>Python en Jupyter Notebook</code></p>
<p>Creado por <code>Giancarlo Ortiz</code> para el curso de <code>Métodos Numéricos</code></p>
<style type="text/css">
    .border {
        display: inline-block;
        border: solid 1px rgba(204, 204, 204, 0.4);
        border-bottom-color: rgba(187, 187, 187, 0.4);
        border-radius: 3px;
        box-shadow: inset 0 -1px 0 rgba(187, 187, 187, 0.4);
        background-color: inherit !important;
        vertical-align: middle;
        color: inherit !important;
        font-size: 11px;
        padding: 3px 5px;
        margin: 0 2px;
    }
</style>

## Solución de sistemas de ecuaciones
En matemáticas y álgebra lineal, solucionar un sistema de ecuaciones consiste en encontrar los valores desconocidos de las variables $x_n$ que satisfacen un conjunto de ecuaciones lineales en donde cada ecuación es de primer grado.

## Agenda
1. Generalidades de sistemas de ecuaciones
1. Generalidades de los métodos de solución
1. Método de Gauss
1. Método de Gauss-Jordan
1. Método de Inversión de matrices
1. Regla de Cramer
1. Método de Montante

In [1]:
# Importar módulos al cuaderno de jupyter
import math as m 
import numpy as np
from numpy import ndarray
from numpy.core.records import array
import pylab as plt

## 1. Generalidades de un sistema de ecuaciones lineales
---
Sean $x_1, x_2, \dots ,x_n$ un conjunto de $\color{#a78a4d}{n}$ incógnitas y los números $a_{ij}$ los coeficientes; se define un sistema de ecuaciones lineales $\color{#a78a4d}{m}$ x $\color{#a78a4d}{n}$, como un conjunto de $\color{#a78a4d}{m}$ ecuaciones de primer grado definidas sobre un anillo conmutativo.

\begin{matrix}
& a_{11}. x_1 &+ a_{12}. x_2 &+ a_{13}. x_3 &+ ... &+ a_{1n}. x_n &= b_1 \\
& a_{21}. x_1 &+ a_{22}. x_2 &+ a_{23}. x_3 &+ ... &+ a_{1n}. x_n &= b_2 \\
&\dots &\dots &\dots &\dots &\dots &\dots \\
& a_{m1}. x_1 &+ a_{m2}. x_2 &+ a_{m3}. x_3 &+ ... &+ a_{mn}. x_n &= b_m \\
\end{matrix}

### a. Matriz de coeficientes
Sea una matriz un arreglo rectangular de números, la matriz **A** de coeficientes se define como un arreglo rectangular que sucesivamente en cada fila organiza los coeficientes de una ecuación.

\begin{pmatrix}
a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}
\end{pmatrix}

### b. Notación matricial
Sea **A** la matriz de coeficientes y **b** el vector de los términos independientes, un sistema de ecuaciones se puede expresar como $\color{#a78a4d}{A}$.$\color{#a78a4d}{x}$ = $\color{#a78a4d}{b}$

\begin{equation*}
{\displaystyle {\begin{pmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\end{pmatrix}}{\begin{pmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{pmatrix}}={\begin{pmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{pmatrix}}}
\end{equation*}

### c. Notación de matriz aumentada
En álgebra lineal y en el marco de los sistemas de ecuaciones lineales, la matriz aumentada de una matriz se obtiene al combinar la matriz de coeficientes A y el vector de los términos independientes B como se muestra a continuación

\begin{equation*}
\left(
\begin{array}{cccc|c}
a_{11} & a_{12} & \dots & a_{1n} & b_1 \\
a_{21} & a_{22} & \dots & a_{2n} & b_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn} & b_m \\
\end{array}
\right)
\end{equation*}

### d. Menores y cofactores
Los menores de una matriz resultan de obtener el determinante de una submatriz de la matriz original que se obtiene de eliminar una o mas filas y una o mas columnas de esa matriz:

* Los menores obtenidos por la eliminación de únicamente una fila y una columna de matrices cuadradas se llaman primeros menores.

* El primer menor $m_{ij}$ de $A$ es el determinante de la matriz $M_{\color{#a78a4d}{(n-1)}\times\color{#a78a4d}{(n-1)}}$ que resulta al eliminar de $A$, la i-ésima fila y la j-ésima columna.

\begin{equation*}
m_{ij} = | M_{ij} |
\end{equation*}

* El cofactor $C_{ij}$ de A es un escalar definido en terminos del menor $m_{ij}$.
\begin{equation*}
C_{ij} = (- 1)^{i+j} \cdot m_{ij}
\end{equation*}



In [2]:
# Definición de la matriz M(i,j) de A
def _M(A: ndarray, i: int, j: int):
    ''' Define la matriz M de la matriz A como Ă(i, j). 
    
        ## Parámetros:
            A (array): una matriz.
            i (int): el primer indice.
            j (int): el segundo indice.
        
        ## Devoluciones:
            M (array): retorna  la matriz M. 
    '''
    M = np.delete(A, i-1, axis=0)
    M = np.delete(M, j-1, axis=1)
    return M

# Definición del menor de una matriz A
def _menor(A: ndarray, i: int, j: int):
    ''' Define la matriz M de la matriz A como Ă(i, j). 
    
        ## Parámetros:
            A (array): una matriz.
            i (int): el primer indice.
            j (int): el segundo indice.
        
        ## Devoluciones:
            m (float): retorna el menor. 
    '''
    M = _M(A, i, j)
    m = np.linalg.det(M)
    return m

# Definición del cofactor de una matriz A
def _cofactor(A: ndarray, i: int, j: int):
    ''' Define el cofactor A(i, j) de una matriz A dada. 
        
        ## Parámetros:
            A (array): una matriz.
            i (int): el primer indice.
            j (int): el segundo indice.
        
        ## Devoluciones:
            C (float): retorna el cofactor. 
    '''
    m = round(_menor(A, i, j), 3)
    C = pow(-1, i+j) * m
    return C


## 2. Generalidades de los métodos de solución
---
En el propósito de solución de un sistema de ecuaciones, estos se pueden clasificar según el número de soluciones que pueden presentar; en este sentido se pueden presentar los siguientes casos:

* Sistema **compatible** si tiene solución, en este caso puede distinguirse entre única solución y un conjunto infinito de soluciones.
* Sistema **incompatible** si no tiene solución.

### a. Matriz diagonal normalizada
En álgebra lineal y en el marco de los sistemas de ecuaciones lineales, una matriz cuadrada se dice que es [diagonal](https://es.wikipedia.org/wiki/Matriz_diagonal) si los elementos de la matriz son todos nulos salvo en la diagonal principal; si adicionalmente los elementos de la diagonal principal son todos 1 se dice que esta normalizada.

\begin{equation*}
\left(
\begin{array}{cccc|c}
1 & 0 & \dots & 0 & i_1 \\
0 & 1 & \dots & 0 & i_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & \dots & 1 & i_m \\
\end{array}
\right)
\end{equation*}

### b. Matriz triangular o escalonada superior normalizada
En álgebra lineal y en el marco de los sistemas de ecuaciones lineales, una matriz se dice que es [escalonada](https://es.wikipedia.org/wiki/Matriz_escalonada), escalonada por filas o que está en forma escalonada superior si los elementos debajo de la diagonal principal son nulos, si adicionalmente los elementos de la diagonal principal son todos 1 se dice que esta normalizada.

\begin{equation*}
\left(
\begin{array}{cccc|c}
1 & e_{12} & \dots & e_{1n} & i_1 \\
0 & 1 & \dots & e_{2n} & i_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & \dots & 1 & i_m \\
\end{array}
\right)
\end{equation*}


### c. Determinante
En álgebra lineal, se define el determinante de una matriz cuadrada **A**$\color{#a78a4d}{_n}_\times\color{#a78a4d}{_n}$ como un valor escalar que codifica el factor de escala de volumen de la transformación lineal descrita por la matriz **A** en un espacio vectorial, el valor es positivo o negativo según si la transformación lineal conserva o invierte la orientación del espacio vectorial; siendo el caso mas trivial el determinante de segundo orden.

\begin{aligned}
|A|={\begin{vmatrix}a&b\\c&d\end{vmatrix}}=ad-bc
\end{aligned}

* El determinante de tercer orden

\begin{aligned}
|A|={\begin{vmatrix}a&b&c\\d&e&f\\g&h&i\end{vmatrix}} &= a {\begin{vmatrix}e&f\\h&i\end{vmatrix}} -b {\begin{vmatrix}d&f\\g&i\end{vmatrix}} +c{\begin{vmatrix}d&e\\g&h \end{vmatrix}} \\
&= a(ei-fh) -b(di-fg) +c(dh-eg) \\
&= aei-afh -bdi+bfg +cdh-ceg \\
&= (aei+bfg+cdh) - (afh+bdi+ceg)
\end{aligned}

* Como una generalización de los casos anteriores la [expansión de Laplace](https://es.wikipedia.org/wiki/Teorema_de_Laplace) expresa el determinante de una matriz en términos de sus menores

\begin{equation*}
\det(A) = |A| = \sum_{i=1}^{n}(- 1)^{i+j} \cdot a_{ij} \cdot | M_{ij} | = \sum_{j=1}^{n}(-1)^{i+j} \cdot a_{ij} \cdot | M_{ij} |
\end{equation*}

In [3]:
# Definición de la matriz de cofactores de A
def _matriz_de_cofactores(A: ndarray):
    ''' Define la matriz de cofactores, que se obtiene de sustituir cada termino de A(i,j) por el C(i,j).
    
        ## Parámetros:
            A (array): una matriz.
        
        ## Devoluciones:
            B (array): la matriz de cofactores. 
    '''
    filas = A.shape[0]
    columnas = A.shape[1]
    B = np.zeros_like(A)
    for i in range(filas):
        for j in range(columnas):
            B[i, j] = _cofactor(A, i+1, j+1)
    return B

# Definición de la matriz adjunta de A
def _matriz_adjunta(A: ndarray):
    ''' Define la matriz de adjunta, que se obtiene de la transpuesta de la matriz de cofactores.
    
        ## Parámetros:
            A (array): una matriz.
        
        ## Devoluciones:
            B (array): la matriz adjunta. 
    '''
    B = np.transpose(_matriz_de_cofactores(A))
    return B

# Definición del dterminante de A
def _determinante(A: ndarray):
    ''' Define el determinante de una matriz A dada.
    
        ## Parámetros:
            A (array): una matriz.
        
        ## Devoluciones:
            B (float): el determinante de la matriz. 
    '''
    Filas = len(A)
    Columnas = len(A[0])
    if (Filas == Columnas):   
        if (Filas == 1):
            return A[0][0]
        
        sum = 0
        for i in range(Filas):
            C = pow(-1, i+2) * A[i][0]
            M = _M(A, i+1, 1)
            D = C * _determinante(M)
            sum = D + sum

        return sum
    else:
        return print(f"ERROR: Determinante no esta definido para matrices {filas}x{columnas}")

## 3. Metodo de gauss
---
En álgebra lineal, los método de eliminación gaussiana reduce el sistema a un matriz triangular superior por medio de operaciones elementales en los renglones de la matriz aumentada, finalmente se despeja el valor de la ultima incógnita y se sustituye hacia arriba en las incógnitas de los renglones superiores. 



\begin{equation*}
\left(
\begin{array}{cccc|c}
1 & 2 & 3 & 4 & 10 \\
0 & 1 & 6 & 5 & 7 \\
0 & 0 & 1 & 7 & -8\\
0 & 0 & 0 & 1 & -9 \\
\end{array}
\right)
\end{equation*}

## 4. Método de Gauss-Jordan
---
En álgebra lineal, los método de eliminación de Gauss-Jordan reduce el sistema a un matriz diagonal por medio de operaciones elementales en los renglones de la matriz aumentada.

\begin{equation*}
\left[
\begin{array}{cccc|c}
1 & 0 & 0 & 0 & -2040 \\
0 & 1 & 0 & 0 & 1320 \\
0 & 0 & 1 & 0 & -250 \\
0 & 0 & 0 & 1 & 40 \\
\end{array}
\right]
\end{equation*}



In [4]:
# Función para encontrar la matriz triangular superior equivalente
def _matriz_triangular(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            At = A
            # Matriz triangular superior
            for j in range(Columnas):  
                # range(Columnas) = [0,1, ... , Columnas] range(3, Columnas) = [3, 4, ... , Columnas]
                for i in range(Filas-(1+j)):
                    factor = (At[i+1+j][0+j] / At[0+j][0+j])
                    A[i+1+j] = A[i+1+j] - factor * A[0+j]
                    B[i+1+j] = B[i+1+j] - factor * B[0+j]

            return A, B


        else:
            print("El sistema no tiene solución única")

    else:
        print("No se puede obtener la matriz triangular superior")

# Función para normalizar la matriz 
def _normalizar(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        # Matriz triangular superior normalizada
        for k in range(Columnas):
            B[0+k] = B[0+k] / A[0+k][0+k]
            A[0+k] = A[0+k] / A[0+k][0+k]

        return A, B

    else:
        print("No se puede normalizar la diagonal de la matriz")

# Función para solucionar un sistema de ecuaciones general
def _matriz_diagonal(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            A, B = _matriz_triangular(A, B)
            A, B = _normalizar(A, B)

            At = A
            # Matriz diagonal
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    f = Filas-(i+2+j)
                    c = Columnas-(1+j)
                    numerador = At[f][c]
                    denominador = At[Filas-(1+j)][Columnas-(1+j)]
                    factor = (numerador / denominador)
                    A[Filas - (2+i+j)] = A[Filas - (2+i+j)] - factor * A[Filas-(1+j)]
                    B[Filas - (2+i+j)] = B[Filas - (2+i+j)] - factor * B[Filas-(1+j)]

            return A, B

        else:
            print("El sistema no tiene solución única")

    else:
        print("No le puedo colaborar")


## 5. Método de inversión de matrices
---
En álgebra lineal, el método de la inversa aprovecha la notación matricial de un sistema de ecuaciones y las operaciones entre matrices para exponer un vector solución del sistema.

\begin{align*}
Ax &= b \\
A^{-1}Ax &= A^{-1}b \\
Ix &= A^{-1}b \\
x &= A^{-1}b \\
x &= \frac{Adj(A)^{t}}{|A|} b
\end{align*}

In [5]:
# Función para calcular la inversa
def _inversa(A: ndarray):
    N = _matriz_adjunta(A)
    D = _determinante(A)
    return N/D


## 6. Método de Cramer
---
En álgebra lineal, la regla de Cramer es un teorema que da solución de un sistema de ecuaciones lineal $\color{#a78a4d}{A}$.$\color{#a78a4d}{x}$ = $\color{#a78a4d}{b}$ en términos de determinantes.

\begin{equation*}
x_j = \frac{ \det(A_j) }{ \det(A)} 
\end{equation*}

>**NOTA:** Donde $A_j$ es la matriz resultante de reemplazar la j-ésima columna de $A$ por el vector columna $b$

In [57]:
# Función para calcular el determinante J-esimo
def _matriz_j(Ma, Mb, J):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    
    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        A = np.array(Ma)
        B = np.array(Mb)
        J = J - 1
        AJ = A
        for i in range(Filas):
            AJ[i][J] = B[i]
        
        return AJ

# Función para calcular el determinante J-esimo
def _determinante_j(Ma, Mb, J):
        AJ =_matriz_j(Ma, Mb, J)
        Det_AJ = _determinante(AJ)
        return Det_AJ

# Función para calcular el determinante J-esimo
def _cramer(Ma, Mb):
    Filas = len(Ma)
    Det_A = _determinante(Ma)
    
    X = B
    for j in range(Filas):
        Aj = _determinante_j(Ma, Mb, j)
        X[j-1] = Aj/Det_A       # regla de cramer

    return X
        

## 7. Metodo de la Montante
---
En álgebra lineal, el método montante es un algoritmo para determinar las soluciones de un sistema de ecuaciones lineales, encontrar matrices inversas, matrices de adjuntos y determinantes. La estructura de este es una modificacion del metodo de Gauss; en este caso, la matriz se modifica para que cada entrada $M_{k,k}$ contenga el menor principal principal $|M_{k,k}|$. La corrección del algoritmo se muestra fácilmente por inducción en k.

\begin{equation*}
M_{i,j} = \frac{M_{i,j}  \cdot M_{k,k} - M_{i,k} \cdot M_{k,j}} {M_{k-1,k-1}}
\end{equation*}

In [7]:
# función de la montante
def _montante(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        for k in range(Filas-1):
            for i in range(Filas-1):
                for j in range(Filas-1):
                    A[i][j] = (A[i][j] * A[k][k] - A[i][k] * A[k][j]) / A[k-1][k-1]
        
        return X



### <code>Ejemplo:</code> Sistema de ecuaciones
---
Sea el sistema:

\begin{matrix}
& 1x_1 &- 2x_2 &+ 3x_3 &- 4x_4 &= 21 \\
&-8x_1 &+ 7x_2 &- 6x_3 &+ 5x_4 &= 30 \\
& 2x_1 &+ 4x_2 &+ 6x_3 &+ 8x_4 &= 26 \\
& 7x_1 &+ 5x_2 &+ 3x_3 &+ 1x_4 &= 19 \\
\end{matrix}

La notación matricial $\color{#a78a4d}{A}$.$\color{#a78a4d}{x}$ = $\color{#a78a4d}{b}$ se define como: 

\begin{equation*}
{\displaystyle 
    {\begin{pmatrix}
    1 &- 2 &  3 &- 4\\
    -8 &  7 &- 6 &  5\\
    2 &  4 &  6 &  8\\
    7 &  5 &  3 &  1\\
    \end{pmatrix}}
    {\begin{pmatrix} x_1\\x_2\\x_3\\x_4 \end{pmatrix}} = 
    {\begin{pmatrix} 21\\30\\26\\19 \end{pmatrix}}
}
\end{equation*}

La matriz aumentada see define como:

\begin{equation*}
\left(
\begin{array}{cccc|c}
 1 & -2 &  3 & -4 & 21 \\
-8 &  7 & -6 &  5 & 30 \\
 2 &  4 &  6 &  8 & 26 \\
 7 &  5 &  3 &  1 & 19 \\
\end{array}
\right)
\end{equation*}


In [8]:
# Definimos el sistema en listas
Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]

# Construimos los array de numpy
A = np.array(Ma)
B = np.array(Mb)

# Calculamos el determinante
Det_A = _determinante(A)

# Calculamos los menores y los cofactores de la primera fila
m11 = _menor(A, 1, 1)
c11 = _cofactor(A, 1, 1)
m12 = _menor(A, 1, 2)
c12 = _cofactor(A, 1, 2)
m13 = _menor(A, 1, 3)
c13 = _cofactor(A, 1, 3)
m14 = _menor(A, 1, 4)
c14 = _cofactor(A, 1, 4)

# Calculamos la matriz de cofactores
C = _matriz_de_cofactores(A)

# Calculamos la matriz adjunta
Adj = _matriz_adjunta(A)

# Salida
print(f"-----------------------------------------------------")
print(f"El determinante A es: {Det_A}")
print(f"-----------------------------------------------------")
print(f"El menor y cofactor (1,1) de A es: {m11:7.1f}   y {c11:7.1f}")
print(f"El menor y cofactor (1,2) de A es: {m12:7.1f}   y {c12:7.1f}")
print(f"El menor y cofactor (1,3) de A es: {m13:7.1f}   y {c13:7.1f}")
print(f"El menor y cofactor (1,4) de A es: {m14:7.1f}   y {c14:7.1f}")
print(f"-----------------------------------------------------")
print(f"La matriz de cofactores es:\n {C}\n")
print(f"-----------------------------------------------------")
print(f"La matriz adjunta es:\n {Adj}\n")

-----------------------------------------------------
El determinante A es: 2592.0
-----------------------------------------------------
El menor y cofactor (1,1) de A es:  -432.0   y  -432.0
El menor y cofactor (1,2) de A es:  -360.0   y   360.0
El menor y cofactor (1,3) de A es:   576.0   y   576.0
El menor y cofactor (1,4) de A es:   504.0   y  -504.0
-----------------------------------------------------
La matriz de cofactores es:
 [[-432.  360.  576. -504.]
 [-216.  288.   72. -144.]
 [-108.  -36.  252.  180.]
 [ 216.  288.  -72. -144.]]

-----------------------------------------------------
La matriz adjunta es:
 [[-432. -216. -108.  216.]
 [ 360.  288.  -36.  288.]
 [ 576.   72.  252.  -72.]
 [-504. -144.  180. -144.]]



In [9]:
# Calculamos la inversa
Inv_A = _inversa(A)

# Salida
print(f"-----------------------------------------------------")
print(f"El inversa de A es:\n {Inv_A}\n")
print(f"-----------------------------------------------------")
print(np.linalg.inv(A))

-----------------------------------------------------
El inversa de A es:
 [[-0.16666667 -0.08333333 -0.04166667  0.08333333]
 [ 0.13888889  0.11111111 -0.01388889  0.11111111]
 [ 0.22222222  0.02777778  0.09722222 -0.02777778]
 [-0.19444444 -0.05555556  0.06944444 -0.05555556]]

-----------------------------------------------------
[[-0.16666667 -0.08333333 -0.04166667  0.08333333]
 [ 0.13888889  0.11111111 -0.01388889  0.11111111]
 [ 0.22222222  0.02777778  0.09722222 -0.02777778]
 [-0.19444444 -0.05555556  0.06944444 -0.05555556]]


In [10]:
# Calculamos la matriz triangular
A1, B1 = _matriz_triangular(Ma, Mb)
At1 = np.append(A1, np.array(np.matrix(B1).T), axis=1)

# Calculamos la matriz triangular normalizada
A2, B2 = _normalizar(A1, B1)
At2 = np.append(A2, np.array(np.matrix(B2).T), axis=1)

# Calculamos la matriz diagonal
A3, B3 = _matriz_diagonal(A2, B2)
At3 = np.append(A3, np.array(np.matrix(B3).T), axis=1)

# Salida
print(f"La matriz aumentada triangular es:")
print(At1)
print(f"\nLa matriz aumentada triangular normalizada es:")
print(At2)
print(f"La matriz aumentada diagonal normalizada es:")
print(At3)
print(f"\nEl vector solución correspondiente es:")
print(B3)


La matriz aumentada triangular es:
[[  1.  -2.   3.  -4.  21.]
 [  0.  -9.  18. -27. 198.]
 [  0.   0.  16.  -8. 160.]
 [  0.   0.   0. -18.  90.]]

La matriz aumentada triangular normalizada es:
[[  1.   -2.    3.   -4.   21. ]
 [ -0.    1.   -2.    3.  -22. ]
 [  0.    0.    1.   -0.5  10. ]
 [ -0.   -0.   -0.    1.   -5. ]]
La matriz aumentada diagonal normalizada es:
[[ 1.   0.   0.   0.  -5.5]
 [ 0.   1.   0.   0.   8. ]
 [ 0.   0.   1.   0.   7.5]
 [ 0.   0.   0.   1.  -5. ]]

El vector solución correspondiente es:
[-5.5  8.   7.5 -5. ]


In [11]:
# Obtenemos el vector solución desde la inversa
x2 = np.matmul(Inv_A, B)

# Salida
print(f"\nEl vector solución correspondiente es:")
print(x2)


El vector solución correspondiente es:
[-5.5  8.   7.5 -5. ]


In [61]:
# Obtenemos las matrices A_j
J = 1
AJ = _matriz_j(Ma, Mb, J)
Det_Aj = _determinante(AJ)
xJ = Det_Aj / Det_A

# Obtenemos el vector solución con el método de Cramer
x3 = _cramer(Ma, Mb)

# Salida
print(f"-----------------------------------------------------")
print(f"La matriz de AJ(J={J}) es:\n {AJ}\n")
print(f"-----------------------------------------------------")
print(f"El determinante de AJ(J={J}) es: {Det_Aj}")
print(f"La solucion para de xJ(J={J}) es: {xJ}")
print(f"-----------------------------------------------------")
print(f"\nEl vector solución correspondiente es:")
print(x3)


-----------------------------------------------------
La matriz de AJ(J=1) es:
 [[21. -2.  3. -4.]
 [30.  7. -6.  5.]
 [26.  4.  6.  8.]
 [19.  5.  3.  1.]]

-----------------------------------------------------
El determinante de AJ(J=1) es: -14256.0
La solucion para de xJ(J=1) es: -5.5
-----------------------------------------------------

El vector solución correspondiente es:
[-5.5  8.   7.5 -5. ]


In [14]:
Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]



In [15]:
# Función para solucionar un sistema de ecuaciones general
def _sistema_ecuaciones_gauss_jordan(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            At = A
            # Matriz triangular superior
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    factor = (At[i+1+j][0+j] / At[0+j][0+j])
                    A[i+1+j] = A[i+1+j] - factor * A[0+j]
                    B[i+1+j] = B[i+1+j] - factor * B[0+j]

            print(A)
            print(B)
            print("------------")

            # Matriz triangular superior normalizada
            for k in range(Columnas):
                B[0+k] = B[0+k] / A[0+k][0+k]
                A[0+k] = A[0+k] / A[0+k][0+k]

            print(A)
            print(B)
            print("------------")

            At = A
            # Matriz diagonal
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    f = Filas-(i+2+j)
                    c = Columnas-(1+j)
                    numerador = At[f][c]
                    denominador = At[Filas-(1+j)][Columnas-(1+j)]
                    factor = (numerador / denominador)
                    A[Filas - (2+i+j)] = A[Filas - (2+i+j)] - factor * A[Filas-(1+j)]
                    B[Filas - (2+i+j)] = B[Filas - (2+i+j)] - factor * B[Filas-(1+j)]

        else:
            print("El sistema no tiene solución única")

    else:
        print("No le puedo colaborar")


    print(f"La matriz aumentada es:")
    print(Ma)
    print(f"\nLa matriz triangular superior:")
    print(B)
    print(f"\nLa matriz diagonal:")
    print(A)
    print(f"\nEl vector solución:")
    print(B)






In [16]:
#Ma = [[2., 1., -1.], [-3., -1., 2.], [-2., 1., 2.]]
#Mb = [8., -11., -3.]

Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]

_sistema_ecuaciones_gauss_jordan(Ma, Mb)

[[  1.  -2.   3.  -4.]
 [  0.  -9.  18. -27.]
 [  0.   0.  16.  -8.]
 [  0.   0.   0. -18.]]
[ 21. 198. 160.  90.]
------------
[[ 1.  -2.   3.  -4. ]
 [-0.   1.  -2.   3. ]
 [ 0.   0.   1.  -0.5]
 [-0.  -0.  -0.   1. ]]
[ 21. -22.  10.  -5.]
------------
La matriz aumentada es:
[[1.0, -2.0, 3.0, -4.0], [-8.0, 7.0, -6, 5.0], [2.0, 4.0, 6.0, 8.0], [7.0, 5.0, 3.0, 1.0]]

La matriz triangular superior:
[-5.5  8.   7.5 -5. ]

La matriz diagonal:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]

El vector solución:
[-5.5  8.   7.5 -5. ]


---
## Mas Recursos

- [Sistema de ecuaciones lineales](https://es.wikipedia.org/wiki/Sistema_de_ecuaciones_lineales) (Wikipedia)
- [Método de Gauss-Jordan](https://es.wikipedia.org/wiki/Eliminaci%C3%B3n_de_Gauss-Jordan) (Wikipedia)
- [Teorema de la función inversa](https://es.wikipedia.org/wiki/Teorema_de_la_funci%C3%B3n_inversa) (Wikipedia)
- [Método de Cramer](https://es.wikipedia.org/wiki/Regla_de_Cramer) (Wikipedia)
- [Método Montante](https://es.wikipedia.org/wiki/M%C3%A9todo_Montante) (Wikipedia)