# Sistemas de ecuaciones
<p><code>Python en Jupyter Notebook</code></p>
<p>Creado por <code>Giancarlo Ortiz</code> para el curso de <code>Métodos Numéricos</code></p>
<style type="text/css">
    .border {
        display: inline-block;
        border: solid 1px rgba(204, 204, 204, 0.4);
        border-bottom-color: rgba(187, 187, 187, 0.4);
        border-radius: 3px;
        box-shadow: inset 0 -1px 0 rgba(187, 187, 187, 0.4);
        background-color: inherit !important;
        vertical-align: middle;
        color: inherit !important;
        font-size: 11px;
        padding: 3px 5px;
        margin: 0 2px;
    }
</style>

## Solución de sistemas de ecuaciones
En matemáticas y álgebra lineal, solucionar un sistema de ecuaciones consiste en encontrar los valores desconocidos de las variables $x_n$ que satisfacen un conjunto de ecuaciones lineales en donde cada ecuación es de primer grado.

## Agenda
1. Generalidades
1. Método de Gauss
1. Método de Gauss-Jordan
1. Método de Inversión de matrices
1. Regla de Cramer
1. Método de Montante

In [2]:
# Importar módulos al cuaderno de jupyter
import math as m 
import numpy as np
import pylab as plt

## 1. Generalidades
---

### a. Sistema de ecuaciones lineales
Un sistema de ecuaciones lineales mxn, es un conjunto de ecuaciones de primer grado definidas sobre un anillo conmutativo.

\begin{align}
a_{11}. x_1 &+ a_{12}. x_2 &+ a_{13}. x_3 &+ ... &+ a_{1n}. x_n &= b_1 \\
a_{21}. x_1 &+ a_{22}. x_2 &+ a_{23}. x_3 &+ ... &+ a_{1n}. x_n &= b_2 \\
&\dots &\dots &\dots &\dots &\dots \\
a_{31}. x_1 &+ a_{32}. x_2 &+ a_{33}. x_3 &+ ... &+ a_{13}. x_3 &= b_3 \\
\end{align}

Una matriz es un arreglo rectangular de números


## 1. Metodo de gauss
---
Los método de eliminación gaussiana reduce el sistema a un matriz triangular superior por medio de operaciones elementales en los renglones de la matriz aumentada, finalmente se despeja el valor de la ultima incognita y se sustituye hacia arriba en las icognitas de los renglones superiores. 

\begin{equation*}
\left[
\begin{array}{cccc|c}
1 & 2 & 3 & 4 & 10 \\
0 & 1 & 6 & 5 & 7 \\
0 & 0 & 1 & 7 & -8\\
0 & 0 & 0 & 1 & -9 \\
\end{array}
\right]
\end{equation*}

## 2. Método de Gauss-Jordan
---
Los método de eliminación de Gauss-Jordan reduce el sistema a un matriz diagonal por medio de operaciones elementales en los renglones de la matriz aumentada.

\begin{equation*}
\left[
\begin{array}{cccc|c}
1 & 0 & 0 & 0 & -2040 \\
0 & 1 & 0 & 0 & 1320 \\
0 & 0 & 1 & 0 & -250 \\
0 & 0 & 0 & 1 & 40 \\
\end{array}
\right]
\end{equation*}

## 3. Método de Newton-Raphson
---
En matemáticas, el método de bisección es un algoritmo de búsqueda de raíces que trabaja dividiendo el intervalo a la mitad y seleccionando el subintervalo que tiene la raíz.

\begin{equation*}
f(x_1, x_2, ... , x_n) = g(x_1, x_2, ... , x_n) \\
\end{equation*}

### Ventajas:
* Metodo estable, siempre converge.
* Útil como aproximación inicial de otros métodos.

### Desventajas:
* No tiene en cuenta la magnitud de los valores de la función en las aproximaciones calculadas $x_n$, solo tiene en cuenta el signo de $f(x)$.
* Método linealmente convergente
* Orden de convergencia, $r = 1$.
* Tasa de convergencia $\mu = 0.5$


## 3. Metodo de la Secante
---
### a. Ecuaciones lineales
Un caso particular de las ecuaciones algebraicas sucede cuando solo los dos primeros coeficientes son distintos de cero y la solucion para x es unica y trivial.

\begin{align}
a_0 + a_1 x & = 0, \quad a_1 \neq 0 \\
x & = \frac{-a_0}{a_1} \\
\end{align}

### b. Ecuaciones cuadraticas
Un caso particular de las ecuaciones algebraicas sucede cuando solo los tres primeros coeficientes son distintos de cero y las 2 soluciones para x no son compleja.

\begin{align}
a_0 + a_1 x + a_2 x^2 & = 0, \quad a_1 \neq 0 \\
x_1, x_2 & = \frac{-a_1 \pm \sqrt{a_1^2 - 4 a_2 a_0 }}{2 a_2} \\
\end{align}

In [32]:
# Función para encontrar la matris triagular superior equivalente
def _matriz_triangular(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            At = A
            # Matriz triangular superior
            for j in range(Columnas):  
                # range(Columnas) = [0,1, ... , Columnas] range(3, Columnas) = [3, 4, ... , Columnas]
                for i in range(Filas-(1+j)):
                    factor = (At[i+1+j][0+j] / At[0+j][0+j])
                    A[i+1+j] = A[i+1+j] - factor * A[0+j]
                    B[i+1+j] = B[i+1+j] - factor * B[0+j]

            return A, B


        else:
            print("El sistema no tiene solución única")

    else:
        print("No se puede obtener la matriz triangular superior")

# Función para normalizar la matriz 
def _normalizar(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        # Matriz triangular superior normalizada
        for k in range(Columnas):
            B[0+k] = B[0+k] / A[0+k][0+k]
            A[0+k] = A[0+k] / A[0+k][0+k]

        return A, B

    else:
        print("No se puede normalizar la diagonal de la matriz")

# Función para solucionar un sistema de ecuaciones general
def _matriz_diagonal(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            A, B = _matriz_triangular(A, B)
            A, B = _normalizar(A, B)

            At = A
            # Matriz diagonal
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    f = Filas-(i+2+j)
                    c = Columnas-(1+j)
                    numerador = At[f][c]
                    denominador = At[Filas-(1+j)][Columnas-(1+j)]
                    factor = (numerador / denominador)
                    A[Filas - (2+i+j)] = A[Filas - (2+i+j)] - factor * A[Filas-(1+j)]
                    B[Filas - (2+i+j)] = B[Filas - (2+i+j)] - factor * B[Filas-(1+j)]

            return A, B

        else:
            print("El sistema no tiene solución única")

    else:
        print("No le puedo colaborar")


In [38]:
Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]

Ma, Mb = _matriz_triangular(Ma, Mb)
A, B = _normalizar(Ma, Mb)

print(f"La matriz A triangular es:")
print(Ma)
print(f"\nLa matriz B correspondiente es:")
print(Mb)
print(f"\nLa matriz A triangular normalizada es:")
print(A)
print(f"\nLa matriz B correspondiente es:")
print(B)



La matriz A triangular es:
[[  1.  -2.   3.  -4.]
 [  0.  -9.  18. -27.]
 [  0.   0.  16.  -8.]
 [  0.   0.   0. -18.]]

La matriz B correspondiente es:
[ 21. 198. 160.  90.]

La matriz A triangular normalizada es:
[[ 1.  -2.   3.  -4. ]
 [-0.   1.  -2.   3. ]
 [ 0.   0.   1.  -0.5]
 [-0.  -0.  -0.   1. ]]

La matriz B correspondiente es:
[ 21. -22.  10.  -5.]


In [37]:
Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]

A, B = _matriz_diagonal(Ma, Mb)

print(f"La matriz A diagonal es:")
print(A)
print(f"\nLa matriz B correspondiente es:")
print(B)

La matriz A diagonal es:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]

La matriz B correspondiente es:
[-5.5  8.   7.5 -5. ]


In [11]:
# Función para solucionar un sistema de ecuaciones general
def _sistema_ecuaciones_gauss_jordan(Ma, Mb):
    Filas = len(Ma)
    Columnas = len(Ma[0])
    A = np.array(Ma)
    B = np.array(Mb)

    # Comprobación de matriz cuadrada, y LI
    if Filas == Columnas:
        if np.linalg.det(A) != 0:

            At = A
            # Matriz triangular superior
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    factor = (At[i+1+j][0+j] / At[0+j][0+j])
                    A[i+1+j] = A[i+1+j] - factor * A[0+j]
                    B[i+1+j] = B[i+1+j] - factor * B[0+j]

            print(A)
            print(B)
            print("------------")

            # Matriz triangular superior normalizada
            for k in range(Columnas):
                B[0+k] = B[0+k] / A[0+k][0+k]
                A[0+k] = A[0+k] / A[0+k][0+k]

            print(A)
            print(B)
            print("------------")

            At = A
            # Matriz diagonal
            for j in range(Columnas):
                for i in range(Filas-(1+j)):
                    f = Filas-(i+2+j)
                    c = Columnas-(1+j)
                    numerador = At[f][c]
                    denominador = At[Filas-(1+j)][Columnas-(1+j)]
                    factor = (numerador / denominador)
                    A[Filas - (2+i+j)] = A[Filas - (2+i+j)] - factor * A[Filas-(1+j)]
                    B[Filas - (2+i+j)] = B[Filas - (2+i+j)] - factor * B[Filas-(1+j)]

        else:
            print("El sistema no tiene solución única")

    else:
        print("No le puedo colaborar")


    print(f"La matriz aumentada es:")
    print(Ma)
    print(f"\nLa matriz triangular superior:")
    print(B)
    print(f"\nLa matriz diagonal:")
    print(A)
    print(f"\nEl vector solución:")
    print(B)






In [15]:
#Ma = [[2., 1., -1.], [-3., -1., 2.], [-2., 1., 2.]]
#Mb = [8., -11., -3.]

Ma = [[1., -2., 3., -4.], [-8., 7., -6, 5.], [2., 4., 6., 8.], [7., 5., 3., 1.]]
Mb = [21., 30., 26., 19.]

_sistema_ecuaciones_gauss_jordan(Ma, Mb)

[[  1.  -2.   3.  -4.]
 [  0.  -9.  18. -27.]
 [  0.   0.  16.  -8.]
 [  0.   0.   0. -18.]]
[ 21. 198. 160.  90.]
------------
[[ 1.  -2.   3.  -4. ]
 [-0.   1.  -2.   3. ]
 [ 0.   0.   1.  -0.5]
 [-0.  -0.  -0.   1. ]]
[ 21. -22.  10.  -5.]
------------
La matriz aumentada es:
[[1.0, -2.0, 3.0, -4.0], [-8.0, 7.0, -6, 5.0], [2.0, 4.0, 6.0, 8.0], [7.0, 5.0, 3.0, 1.0]]

La matriz triangular superior:
[-5.5  8.   7.5 -5. ]

La matriz diagonal:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]

El vector solución:
[-5.5  8.   7.5 -5. ]


---
## Mas Recursos

- [Sistema de ecuaciones lineales](https://es.wikipedia.org/wiki/Sistema_de_ecuaciones_lineales) (Wikipedia)
- [Método de Gauss-Jordan](https://es.wikipedia.org/wiki/Eliminaci%C3%B3n_de_Gauss-Jordan) (Wikipedia)
- [Teorema de la función inversa](https://es.wikipedia.org/wiki/Teorema_de_la_funci%C3%B3n_inversa) (Wikipedia)
- [Método de Cramer](https://es.wikipedia.org/wiki/Regla_de_Cramer) (Wikipedia)
- [Método Montante](https://es.wikipedia.org/wiki/M%C3%A9todo_Montante) (Wikipedia)